version: '3'
services:
  voter:
    image: vjkumar24/voterservice:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3

  resume:
    image: vjkumar24/resumeservice:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3  
